// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gwbMpcq_APFv3e7AwTOTviUhCiEitYk',
    appId: '1:1098684538639:web:7e858f614519921d3be87a',
    messagingSenderId: '1098684538639',
    projectId: 'push-c1486',
    authDomain: 'push-c1486.firebaseapp.com',
    storageBucket: 'push-c1486.appspot.com',
    measurementId: 'G-KY74RXEK3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASb3XX8n4Jv0xTts9d1Rn_ZZlVg5ZLd-4',
    appId: '1:1098684538639:android:a9503c9282a4772a3be87a',
    messagingSenderId: '1098684538639',
    projectId: 'push-c1486',
    storageBucket: 'push-c1486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsuaEDcbePJUheqbPaXByx9EaP2s3uOnM',
    appId: '1:1098684538639:ios:1ff146134c42fe333be87a',
    messagingSenderId: '1098684538639',
    projectId: 'push-c1486',
    storageBucket: 'push-c1486.appspot.com',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsuaEDcbePJUheqbPaXByx9EaP2s3uOnM',
    appId: '1:1098684538639:ios:c19d61c5e3b70cdd3be87a',
    messagingSenderId: '1098684538639',
    projectId: 'push-c1486',
    storageBucket: 'push-c1486.appspot.com',
    iosBundleId: 'com.example.pushnotification.RunnerTests',
  );
}
